"""add join_code and exam_enrollments

Revision ID: 0cb4f462b237
Revises: ccf89f5f7712
Create Date: 2026-07-27 17:14:13.292625

"""
from alembic import op
import sqlalchemy as sa


revision = '0cb4f462b237'
down_revision = 'ccf89f5f7712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exams', sa.Column('join_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_exams_join_code'), 'exams', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_join_code'), table_name='exams')
    op.drop_column('exams', 'join_code')
    op.drop_table('exam_enrollments')
    # ### end Alembic commands ###
