"""add review status to exam sessions

Revision ID: ccf89f5f7712
Revises: 0957461e3896
Create Date: 2026-07-27 15:20:52.721742

"""
from alembic import op
import sqlalchemy as sa


revision = 'ccf89f5f7712'
down_revision = '0957461e3896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('exam_sessions', sa.Column('review_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'review_note')
    op.drop_column('exam_sessions', 'review_status')
    # ### end Alembic commands ###
